{"uuid": "3f6c46fd-8939-4630-98e3-24b1372abb74", "children": ["475723cc-55dd-4874-a8a3-c9f76a01bdd8"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))\n", "trace": "  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Deepak\\PycharmProjects\\pytest_experiment\\Testcases\\conftest.py\", line 35, in get_browser\n    driver.get(configReader.readConfig(\"basic info\",\"testsiteurl\"))\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\util\\retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\packages\\six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\site-packages\\urllib3\\connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\http\\client.py\", line 1377, in getresponse\n    response.begin()\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\http\\client.py\", line 320, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\http\\client.py\", line 281, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\Deepak\\anaconda3\\lib\\socket.py\", line 704, in readinto\n    return self._sock.recv_into(b)\n"}, "start": 1684367586897, "stop": 1684367632442}], "start": 1684367586897, "stop": 1684367633049}